sub wsyokuzero{$dmg2 += int(rand($wn_0)) + $wi_dmg;}
sub wsyokuone{$dmg2 += int(rand($wn_1)) + $wi_dmg;}
sub wsyokutwo{$dmg2 += int(rand($wn_2)) + $wi_dmg;}
sub wsyokuthree{$dmg2 += int(rand($wn_4)) + $wi_dmg;}
sub wsyokufour{$dmg2 += int(rand($wn_1)) + $wi_dmg;}
sub wsyokufive{$dmg2 += int(rand($wn_1)) + $wi_dmg;}
sub wsyokusix{$dmg2 += int(rand($wn_2)) + int(rand($wn_6)) + $wi_dmg;}
sub wsyokuseven{$dmg2 += int(rand($wn_1)) + int(rand($wn_6)) + $wi_dmg;}
sub wsyokueight{$dmg2 += int(rand($wn_0)) + int(rand($wn_4)) + $wi_dmg;}
sub wsyokunine{$dmg2 += int(rand($wn_1)) + int(rand($wn_2)) + $wi_dmg;}
sub wsyokuten{$dmg2 += int(rand($wn_0)) + int(rand($wn_2)) + $wi_dmg;}
sub wsyokueleven{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + $wi_dmg;}
sub wsyokutwelve{$dmg2 += int(rand($wn_0)) + int(rand($wn_3)) + $wi_dmg;}
sub wsyokuthirteen{$dmg2 += int(rand($wn_0)) + int(rand($wn_4)) + $wi_dmg;}
sub wsyokufourteen{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + $wi_dmg;}
sub wsyokufifteen{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + $wi_dmg;}
sub wsyokusixteen{$dmg2 += int(rand($wn_0)) + int(rand($wn_4)) + $wi_dmg;}
sub wsyokuseventeen{$dmg2 += int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_6)) + $wi_dmg;}
sub wsyokueighteen{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp) + $wi_dmg;}
sub wsyokunineteen{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp) + $wi_dmg;}
sub wsyokutwenty{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp) + $wi_dmg;}
sub wsyokutwentyone{$dmg2 += int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp) + $wi_dmg;}
sub wsyokutwentytwo{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 2) + $wi_dmg;}
sub wsyokutwentythree{$dmg2 += int(rand($wn_0)) + $wi_dmg;}
sub wsyokutwentyfour{$dmg2 += ((int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 2) + $wi_dmg;}
sub wsyokutwentyfive{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int((rand($wn_4))*5) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 2) + $wi_dmg;}
sub wsyokutwentysix{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 2) + $wi_dmg;}
sub wsyokutwentyseven{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 3) + $wi_dmg;}
sub wsyokutwentyeight{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 3) + $wi_dmg;}
sub wsyokutwentynine{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 4) + $wi_dmg;}
sub wsyokuthirty{$dmg2 += ((int(rand($wn_0)) + int(rand($wn_1)) + int(rand($wn_2)) + int(rand($wn_3)) + int(rand($wn_4)) + int(rand($wn_5)) + int(rand($wn_6)) + int($wlp)) * 5) + $wi_dmg;}
1;